{{- if and .Values.clickhouse.enabled .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "purl.clickhouse.fullname" . }}
  labels:
    {{- include "purl.clickhouse.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "purl.clickhouse.selectorLabels" . | nindent 6 }}
{{- end }}
