{{- if and .Values.clickhouse.enabled .Values.clickhouse.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "purl.clickhouse.fullname" . }}-data
  labels:
    {{- include "purl.clickhouse.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.clickhouse.persistence.accessModes | nindent 4 }}
  {{- if .Values.clickhouse.persistence.storageClass }}
  storageClassName: {{ .Values.clickhouse.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.clickhouse.persistence.size }}
{{- end }}
