{{- if .Values.vector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "purl.fullname" . }}-vector
  labels:
    {{- include "purl.labels" . | nindent 4 }}
    app.kubernetes.io/component: vector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "purl.fullname" . }}-vector
  labels:
    {{- include "purl.labels" . | nindent 4 }}
    app.kubernetes.io/component: vector
rules:
  - apiGroups: [""]
    resources: ["namespaces", "nodes", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "purl.fullname" . }}-vector
  labels:
    {{- include "purl.labels" . | nindent 4 }}
    app.kubernetes.io/component: vector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "purl.fullname" . }}-vector
subjects:
  - kind: ServiceAccount
    name: {{ include "purl.fullname" . }}-vector
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "purl.fullname" . }}-vector
  labels:
    {{- include "purl.labels" . | nindent 4 }}
    app.kubernetes.io/component: vector
spec:
  selector:
    app.kubernetes.io/name: {{ include "purl.name" . }}-vector
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: api
      port: 8686
    - name: metrics
      port: 9598
  clusterIP: None
{{- end }}
