apiVersion: v1
kind: Config
clusters:
  - name: purl-audit
    cluster:
      server: http://purl.purl.svc.cluster.local:3000/api/v1/k8s-audit
contexts:
  - name: default
    context:
      cluster: purl-audit
current-context: default
