apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: purl
  namespace: purl
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: purl
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: clickhouse
  namespace: purl
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: clickhouse
